include: package:very_good_analysis/analysis_options.10.0.0.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    avoid_renaming_method_parameters: false
